name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t hvc-tests .

      - name: Run container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/work \
            -w /work \
            hvc-tests
